bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('update-cart', views.update_cart, name='update_cart'),
    path('delete-cart', views.delete_cart, name='delete_cart'),
]

prints/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'prints.views.handler404'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('add/', views.add_product, name='add_product'),
    path('add-spec/', views.add_product_spec, name='add_product_spec'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>/', views.delete_product, name='delete_product'
        ),
]

products/models.py
from django.db import models


class Category(models.Model):
    """
    Category model
    """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    """
    Product model
    """
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL
        )
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    image = models.ImageField(null=True, blank=False)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Size(models.Model):
    """
    Size model
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Paper(models.Model):
    """
    Paper model
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ProductSpec(models.Model):
    """
    Product specs model
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(null=True, default=0)
    objects = models.Manager()

    def __str__(self):
        return self.product.name

products/forms.py
from django import forms
from .models import Product, Category, ProductSpec


class ProductForm(forms.ModelForm):
    """
    Class form to agregate product fields
    """
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names

        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = True
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class SpecForm(forms.ModelForm):
    """
    Class form to agregate product spec fields
    """
    class Meta:
        model = ProductSpec
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from .models import Product, Category, ProductSpec
from .forms import ProductForm, SpecForm


def all_products(request):
    """
    A view to show all products, including sorting and search queries
    """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

    if request.GET:
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!"
                    )
                return redirect(reverse('products'))
            else:
                queries = (
                    Q(name__icontains=query) | Q(description__icontains=query)
                )
                products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, id):
    """
    A view to show individual product details
    """

    product = Product.objects.get(id=id)
    sizes = (
        ProductSpec.objects.filter(product=product).values(
            'size__id', 'size__name'
            ).distinct()
    )
    papers = (
        ProductSpec.objects.filter(product=product).values(
            'paper__id', 'paper__name', 'price', 'size__id'
            ).distinct()
        )

    context = {
        'product': product,
        'sizes': sizes,
        'papers': papers,
    }

    return render(request, 'products/product_detail.html', context)


def add_to_cart(request):
    """
    View to add prints to the cart
    """
    # del request.session['bag']
    paper_id = request.GET['paper-id']
    size_id = request.GET['size-id']
    product_id = request.GET['id']
    product_qty = int(request.GET['qty'])
    product_price = request.GET['price']
    product_name = request.GET['name']
    product_size = request.GET['size']
    product_paper = request.GET['paper']
    product_spec = ProductSpec.objects.filter(
        paper__id=paper_id, size__id=size_id, product__id=product_id
        ).first()
    product_spec_id = str(product_spec.id)
    cart_data = {}

    cart_data[product_spec_id] = {
        'qty': product_qty,
        'price': product_price,
        'name': product_name,
        'size': product_size,
        'paper': product_paper
    }
    bag = request.session.get('bag', {})

    if product_spec_id in list(bag.keys()):

        bag[product_spec_id]['qty'] += product_qty
        messages.success(
            request, (
                f'Added {product_name} with: {product_paper} paper type and {product_size}) size to your bag'
                )
            )

    else:
        bag.update(cart_data)
        messages.success(request, f'Added {product_name} to your bag')

    request.session['bag'] = bag

    return JsonResponse({'data': bag})


@login_required
def add_product(request):
    """ Add a product to the store """
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Successfully added print now choose the Specs!'
                )
            return redirect('add_product_spec')
        else:
            messages.error(
                request, (
                    'Failed to add print. Please ensure the form is valid.'
                    )
                )
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def add_product_spec(request):
    """
    Add product specs to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    if request.method == 'POST':
        form = SpecForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, (
                    'Successfully added print with Specs, add more Specs to the same print!'
                    )
                )
            return redirect(reverse('add_product_spec'))
        else:
            messages.error(
                request, (
                    'Failed to add print. Please ensure the form is valid.'
                    )
                )
    else:
        form = SpecForm()

    template = 'products/add_product_spec.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated print!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, (
                    'Failed to update print. Please ensure the form is valid.'
                    )
                )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
    <div class="container header-container header-top-space">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="overlay"></div>
    <div class="container col-6 header">
        <div class="row">
            <div class="col">
                <hr>
                <h3 class="text-muted">Add a Print</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Go back to all prints</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Print and choose Specs</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/add_product_spec.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
    <div class="container header-container header-top-space">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="overlay"></div>
    <div class="container col-6 header">
        <div class="row">
            <div class="col">
                <hr>
                <h3 class="text-muted">Add Print Specs</h3>
                <p>Important! The order of adding specs must be A3 size first with etching paper,
                    following with A3 with rag paper, after A4 with etching paper and finally A4 with rag paper.""
                </p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="POST" action="{% url 'add_product_spec' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Go back to all prints</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Print Specs</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
    <div class="container header-container header-top-space">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="overlay"></div>
    <div class="container col-6 header">
        <div class="row">
            <div class="col">
                <hr>
                <h3 class="text-muted">Edit a Print</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Go back to all prints</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Print</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/edit_product_spec.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
    <div class="container header-container header-top-space">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="overlay"></div>
    <div class="container col-6 header">
        <div class="row">
            <div class="col">
                <hr>
                <h3 class="text-muted">Edit a Print Spec</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <form method="POST" action="{% url 'edit_product_spec' product_spec.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Go back to all prints</a>
                        <button class="btn btn-black rounded-0" type="submit">Update Print Spec</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block page_header %}
{% endblock %}
{% block content %}
    <div class="container header-top-space header product-detail-width">
        <div class="row">
            <div class="col-12 text-center">
                <div class="image-container my-2">
                    {% if "placeholder" in product.image.url %}
                    <a href="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" target="_blank">
                        <img class="card-img-top img-fluid"
                            src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                    </a>
                    {% else %}
                    <a href="{{ product.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" alt="event" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% endif %}
                </div>
                <hr/>
                <p class="mt-3 text-black">{{ product.name }}</p>
                <hr/>
                <p class="mt-3 text-black">{{ product.description }}</p>
                <hr/>
                <div class="product-details-container mb-5 mt-md-5">
                    <table class="table table-bordered">
                        <tr>
                            <th>Paper Size</th>
                            <td>
                                {% for size in sizes %}
                                    <button product-size="{{size.size__id}}" size-id="{{size.size__id}}" class="btn btn-outline-secondary btn-sm size">{{size.size__name}}</button>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th>Paper Type</th>
                            <td>
                                {% for paper in papers %}
                                <button product-price="{{paper.price}}" paper-id="{{paper.paper__id}}" class="btn btn-outline-secondary btn-sm paper size{{paper.size__id}}">{{paper.paper__name}}</button>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th>Price US$</th>
                            <th><p class="lead mb-0 text-left font-weight-bold product-price-variation text-black price-small">{{product.productspec_set.first.price}}</p></th>
                        </tr>
                    </table>
                    <hr/>
                    <div class="form-row">
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50 mx-auto">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-black rounded-4" 
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input oninput="this.value=(this.value   < Number(this.min) || this.value   > Number(this.max))  ? '' : this.value;" type="number" value="1" min="1" max="99" class="form-control product-qty- qty_input" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}"/>
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-black rounded-4"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                                <hr/>
                                <div class="input-group-append">
                                    <input type="hidden" class="product-id-" value="{{product.id}}" />
                                    <input type="hidden" class="product-name-" value="{{product.name}}" />
                                    <input type="hidden" class="paper-id" />
                                    <input type="hidden" class="size-id" />
                                    <input type="hidden" class="redirect_url" value="{{ request.path }}">
                                    <button class="btn btn-black rounded-0 add-to-cart" data-index="{{product.id}}" type="button"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}
    <div class="container header-top-space">
        <div class="col-12 mt-3">
            <div class="row">
                {% for product in products %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100 border-0">
                                {% if product.image.url %}
                                <a href="{% url 'product_detail' product.id %}">
                                    <img class="card-img-top img-fluid" alt="event" src=" {{ product.image.url }}">
                                </a>
                                {% else %}
                                <a href="{% url 'product_detail' product.id %}">
                                    <img class="card-img-top img-fluid"
                                        src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                </a>
                                {% endif %}
                            <div class="card-body pb-0 header border-0 text-left text-black">
                                <span class="mt-3 text-black"><strong>{{ product.name }}</strong></span>
                                <hr/>
                                <span class="mt-3 text-black">{{ product.description }}</span>
                                {% if product.category %}
                                <p class="small mt-2 mb-1">
                                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                    </a>
                                </p>
                                {% endif %}
                                {% if request.user.is_superuser %}
                                <small class="ml-3">
                                    <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                                    <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                                </small>
                                {% endif %}
                            </div>
                        </div>
                    </div> 
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="btt-button shadow-sm rounded-0 border border-black">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}